---
name: 📦 Update Package
description: Request that a pinned package be bumped
labels: ["is:update", "re:packages", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      Doom pins its packages to certain commits to avoid breaking updates and help its maintainer keep up with changes. These pins are updated (bumped) frequently, usually every other week, but sometimes I'll fall behind, either due to life:tm: or upstream issues. Other times, a package may introduce critical fixes I should be made aware of.

      Use this form to let me know about these updates.

      -----

      **Before you submit this bump request, please ensure that the target packages:**

      - Haven't already been [requested](https://github.com/hlissner/doom-emacs/issues) or [PRed](https://github.com/hlissner/doom-emacs/pulls),
      - *Is not* in [our do-not-PR list](https://doomemacs.org/d/do-not-pr),
      - Hasn't already been bumped in later commits of Doom,
      - Still work with Doom on their latest commits.
- type: textarea
  attributes:
    label: What package(s) should be bumped?
    placeholder: |
      lsp-mode, lsp-python-ms, lsp-pyright, ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Why should Doom bump these packages early?
    description: |
      What has changed upstream? Why do those changes warrant an early bump? Link any relevant commits or issues, if possible. Mention anything Doom may have to change to accommodate it.
    placeholder: |
      Recent changes to X have fixed several open issues in Y and Z, but have broken A and B in Doom.
- type: markdown
  attributes:
    value: |
      Please take a moment to ensure your bump request is **well-researched, descriptive, and specific**, otherwise, you risk it being significantly delayed or automatically closed.

      Emacs' complexity and extensibility produces many false positive or vague requests, so I will immediately close issues that aren't **actionable**, **poorly explained**, or able to be investigated in a reasonable amount of **time**.

      If you don't think your request qualifies, please bring it up on [our Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) instead.

      :heart: **Thank you for taking the time to make this bump request!**
